### ISSUE TITLE
TN3 Launch Checklist

### ISSUE THREAD

**Issue by avive** [karma-coin/karmachain#165]
This is a master task list for launching TN3:
- [x] Check all configuration is done - Treasury, Sudo, Slashing, Era and Epoch times, supported validator public key, etc...
- [x] Deploy the supported validator microservice over https using karmaco.in dns. e.g. validator.karmaco.in and test it.
- [x] Add more things here...
