### ISSUE TITLE
TN3 Operational Checklist

### ISSUE THREAD

**Issue by avive** [karma-coin/karmachain#166]
Prior to TN3 launch
- [x] obtain latest KC1 ledger and import it on genesis to test importing.

Post TN3 launch we need to verify the following:
- [x] Validation rewards issuance.
- [x] Slashing.
- [x] Blocks finalization.
- [x] Karma rewards.
- [x] External validator joining.
- [x] External validator leaving.
- [x] Legacy account importing - check balances.
- [x] Update docs for validators

**Comment by HolyGrease** [comment]
To test karma rewards we have to wait for 1 month so I assume it works as on dev chain it works properly

**Comment by HolyGrease** [comment]
Slashing fixed in https://github.com/karma-coin/karmachain/pull/195
